### PR TITLE
Fix runtime exceptions for "newtmgr conn add/delete" and update help text for newtmgr 

### PR DESCRIPTION
**Pull request by cwanda**
1) Fixed runtime exception when no argument is given to the  `newtmgr conn add` and the `newtmgr conn delete` command. 
2) Updated help texts.

### CODE REVIEW

**Comment by mkiiskila** [comment]
Seems like you're fixing some of the go formatting. Could you fix the other things 'gofmt' is not happy with in runtest.go as well? Thanks!

**Comment by cwanda** [comment]
Hi Aditi
I added "remote" to the newtmgr help text

**Comment by cwanda** [comment]
Hi Marko,
Umm, my original commit should have the gofmt cleanup for runtest.go.  I just did a gofmt -d runtest.go on my local branch to verify that I committed the changes, and gofmt -d doesn't indicate any differences. Are you still seeing things that gofmt is not happy with for runtest.go?

**Comment by mkiiskila** [comment]
Maybe our gofmt are of different version? Thanks for doing the changes.

**Pull request merged**
