### PR TITLE
MYNEWT-495: updates to sync command

### PR DESCRIPTION
**Pull request by utzig**
MYNEWT-495: updates to sync command

- When repo is already cloned, try to update from remote
- If "-f" is passed, create a modifications diff, and try harder to update current local (stash, clean, checkout, pull)

### CODE REVIEW

**Comment by utzig** [comment]
Kinda WIP because I'm still doing corner case testing...

**Comment by utzig** [comment]
Just copy/paste of the last commit message:

```
- sync now creates a new branch when checking out a tag commit
- sync flow now:
  1) stash changes
  2) fetch branchs/tags from origin
  3) merges in changes on master and develop
  4) checks out old branch or new branch (creating if necessary)
  5) stash pops if the previous stash was succesful
- upgrade/install now try first to cleanup and existing repo and if it
  fails do the old style remove+clone.
```

Looks good on my tests, no issues so far. Seems good to be merged if no review issues are found.

**Comment by sterlinghughes** [comment]
I don't think we should ever do the old style remove + clone, but I agree with the design otherwise.

**Comment by utzig** [comment]
Well, hopefully the user will not pass `-f` all the time!

**Comment by sterlinghughes** [comment]
I saw that after my comment, i think this commit is gtg.

**Comment by utzig** [comment]
Btw, if I remember correctly `upgrade` always uses `force` == `true` which might be reworked in the future.

**Pull request merged**
